import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {api,tokenStore,money} from '../api/client';
import {Button,State} from '../components/UI';

export default function MyProducts(){
 const nav=useNavigate(); const [data,setData]=useState(null); const [edit,setEdit]=useState(null); const [err,setErr]=useState(''); const [busy,setBusy]=useState(false);
 const load=()=>{if(!tokenStore.get()){nav('/login');return} setData(null);api('/auth/me').then(r=>api('/users/'+r.data.user.id+'/products?limit=50')).then(setData).catch(e=>setErr(e.message))};
 useEffect(load,[]);
 async function remove(id){if(!confirm('Delete this product?'))return;try{await api('/products/'+id,{method:'DELETE'});load()}catch(e){setErr(e.message)}}
 async function sold(id,is_sold){try{await api('/products/'+id+'/sold',{method:'PATCH',body:{is_sold:!is_sold}});load()}catch(e){setErr(e.message)}}
 async function save(e){e.preventDefault();setBusy(true);const fd=new FormData();Object.entries(edit.form).forEach(([k,v])=>v!==''&&fd.append(k,v));edit.files.forEach(f=>fd.append('images',f));try{await api('/products/'+edit.id,{method:'PUT',body:fd,form:true});setEdit(null);load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 return <section className="container page"><div className="page-head"><span className="eyebrow">Seller tools</span><h1>My products</h1><p>Edit, remove or mark your own listings as sold.</p></div>{err&&<div className="alert error">{err}</div>}{edit&&<form className="form panel" onSubmit={save}><h2>Edit product</h2><div className="form-grid"><label>Name<input required value={edit.form.name} onChange={e=>setEdit({...edit,form:{...edit.form,name:e.target.value}})}/></label><label>Price<input required type="number" value={edit.form.price} onChange={e=>setEdit({...edit,form:{...edit.form,price:e.target.value}})}/></label><label>Category ID<input required value={edit.form.category_id} onChange={e=>setEdit({...edit,form:{...edit.form,category_id:e.target.value}})}/></label><label>Condition<select value={edit.form.condition||'new'} onChange={e=>setEdit({...edit,form:{...edit.form,condition:e.target.value}})}><option value="new">New</option><option value="used">Used</option><option value="refurbished">Refurbished</option></select></label><label>Location<input value={edit.form.location||''} onChange={e=>setEdit({...edit,form:{...edit.form,location:e.target.value}})}/></label></div><label>Description<textarea rows="5" value={edit.form.description||''} onChange={e=>setEdit({...edit,form:{...edit.form,description:e.target.value}})}/></label><label className="upload-box">Replace images (optional)<input type="file" accept="image/*" multiple onChange={e=>setEdit({...edit,files:[...e.target.files]})}/></label><div className="detail-actions"><Button type="submit" loading={busy}>Save changes</Button><Button variant="outline" type="button" onClick={()=>setEdit(null)}>Cancel</Button></div></form>}{!data?<State type="loading" title="Loading your products"/>:data.data?.length?<div className="manage-list">{data.data.map(p=><div className="manage-card" key={p.id}><div className="manage-thumb">{p.primary_image?<img src={p.primary_image} alt=""/>:<span>SHINEX</span>}</div><div className="manage-copy"><b>{p.name}</b><strong>{money(p.price)}</strong><span>{p.location||'Location not specified'} · {p.is_sold?'Sold':'Available'}</span></div><div className="actions"><Button variant="outline" onClick={()=>setEdit({id:p.id,form:{name:p.name,price:p.price,category_id:p.category_id,description:p.description||'',condition:p.condition||'new',location:p.location||''},files:[]})}>Edit</Button><Button variant="ghost" onClick={()=>sold(p.id,p.is_sold)}>{p.is_sold?'Mark available':'Mark sold'}</Button><Button variant="danger" onClick={()=>remove(p.id)}>Delete</Button></div></div>)}</div>:<State title="No products yet" body="Create your first listing from the Sell page."><Button onClick={()=>nav('/sell')}>Post a product</Button></State>}</section>
}
